name: Maven Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
    container:
      image: ghcr.io/carlossg/maven:3-azulzulu-11-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn --settings settings.xml --file pom.xml  clean  deploy -Drevision=${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}